version: '3'
volumes:
  postgres-data:
    driver: "local"
services:
  api-go-db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment: 
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api-go:
    build: .  
    volumes: 
      - ./src:/go/src
      - .env:/go/src/api/.env
    ports:
      - "80:80"
    command: go run main.go
    depends_on:
      - db