version: '3'
volumes:
  postgres-data:
    driver: "local"
services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment: 
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  # web:
  #   build: .
  #
  #   volumes: 
  #     - ./src:/go/src
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - db
  web:
    image: golang:1.10-alpine3.7
    volumes: 
      - ./src:/go/src
      - .env:/go/src/api/.env
    ports:
      - "80:80"
    working_dir: /go/src/api
    command: go run main.go
    depends_on:
      - db