version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

volumes:
  postgres-data:
    driver: "local"
services:
  api-go-db:
    image: postgres:10
    environment: 
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api-go:
    build: .  
    volumes:
      - ./src:/go/src
      - .env:/go/src/api/.env
    command: go run main.go
    links:
      - api-go-db
    depends_on:
      - api-go-db
    networks:
      - internal
  api-go-server:
    image: "nginx:1.15.2-alpine"
    volumes:
       - "./api-go.conf:/etc/nginx/conf.d/default.conf"
    links:
      - api-go
    depends_on:
      - api-go
    labels:
      - traefik.enable=true
      - traefik.backend=api-go-server
      - traefik.frontend.rule=Host:api-go.lucasmarques73.com.br
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - internal
      - proxy
